// Generated by gencpp from file navplay/vel.msg
// DO NOT EDIT!


#ifndef NAVPLAY_MESSAGE_VEL_H
#define NAVPLAY_MESSAGE_VEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navplay
{
template <class ContainerAllocator>
struct vel_
{
  typedef vel_<ContainerAllocator> Type;

  vel_()
    : gpst(0.0)
    , forward(0.0)
    , angular(0.0)  {
    }
  vel_(const ContainerAllocator& _alloc)
    : gpst(0.0)
    , forward(0.0)
    , angular(0.0)  {
  (void)_alloc;
    }



   typedef double _gpst_type;
  _gpst_type gpst;

   typedef float _forward_type;
  _forward_type forward;

   typedef float _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::navplay::vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navplay::vel_<ContainerAllocator> const> ConstPtr;

}; // struct vel_

typedef ::navplay::vel_<std::allocator<void> > vel;

typedef boost::shared_ptr< ::navplay::vel > velPtr;
typedef boost::shared_ptr< ::navplay::vel const> velConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navplay::vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navplay::vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navplay::vel_<ContainerAllocator1> & lhs, const ::navplay::vel_<ContainerAllocator2> & rhs)
{
  return lhs.gpst == rhs.gpst &&
    lhs.forward == rhs.forward &&
    lhs.angular == rhs.angular;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navplay::vel_<ContainerAllocator1> & lhs, const ::navplay::vel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navplay

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::navplay::vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navplay::vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navplay::vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navplay::vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navplay::vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navplay::vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navplay::vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e11ee5e5f9a364893511f8eb7b4a576";
  }

  static const char* value(const ::navplay::vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e11ee5e5f9a3648ULL;
  static const uint64_t static_value2 = 0x93511f8eb7b4a576ULL;
};

template<class ContainerAllocator>
struct DataType< ::navplay::vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navplay/vel";
  }

  static const char* value(const ::navplay::vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navplay::vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 gpst\n"
"float32 forward\n"
"float32 angular\n"
;
  }

  static const char* value(const ::navplay::vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navplay::vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gpst);
      stream.next(m.forward);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navplay::vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navplay::vel_<ContainerAllocator>& v)
  {
    s << indent << "gpst: ";
    Printer<double>::stream(s, indent + "  ", v.gpst);
    s << indent << "forward: ";
    Printer<float>::stream(s, indent + "  ", v.forward);
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVPLAY_MESSAGE_VEL_H
